INSERT INTO PROFILES (ID) VALUES ('lameiraatt');
INSERT INTO PROFILES (ID) VALUES ('astroash');
INSERT INTO PROFILES (ID) VALUES ('edwardtsatsu');
INSERT INTO PROFILES (ID) VALUES ('randyayittah');
INSERT INTO PROFILES (ID) VALUES ('aweperi');

